[package]
name = "tasks_macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true
description = "The `task!` procedural macro"

[lib]
proc-macro = true

[dependencies]
tasks_args = { path = "../args" }

[lints]
workspace = true
